apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: rhdh-lab-catalog
spec:
  targets:
    - ./org.yaml
    - ./system.yaml
    - ./hello-rhdh.yaml
    - ../templates/servicos-simples/template.yaml
