apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-lab
---
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh-lab
spec:
  application:
    route:
      enabled: true
    database:
      enableLocalDb: true